[package]
name = "dioxus-docs-site"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-ssr = { path = "../ssr" }
pulldown-cmark = "0.8.0"
recoil = { path = "../recoil" }
codeblocks = { path = "../../../ecosystem-dioxus/syntec-dioxus/" }
