[package]
name = "dioxus"
version = "0.1.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
"license" = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { path="./packages/core", version="0.1.0" }
dioxus-core-macro = { path="./packages/core-macro", version="0.1.0" }
dioxus-hooks = { path="./packages/hooks", version="0.0.0" }


[features]
default = ["ssr", "hooks", "router", "web", "core", "atoms"]
atoms = []
core = []
ssr = []
hooks = []
router = []
web = []
desktop = []

[workspace]
# members = ["packages/core-macro"]
members = [
    "packages/core-macro",
    "packages/core",
    "packages/web",
    "packages/ssr",
    "packages/docsite",
    "packages/atoms",
    "packages/router",
]
# "packages/webview",

# "packages/cli",
# "packages/webview",
# "packages/hooks",
# "packages/ios",

[profile.dev]
split-debuginfo = "unpacked"

# "packages/liveview",
# "packages/3d",

# Built-in
# "packages/webview/client",
# "packages/router",
# "packages/webview",
# "packages/livehost",
# "packages/vscode-ext",
# "packages/recoil",
# "packages/redux",
# "packages/macro",
# TODO @Jon, share the validation code
# "packages/web",
# "packages/cli",
# "examples",
# "packages/html-macro",
