[package]
name = "rink"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.16.0", features = ["crossterm"] }
crossterm = "0.22.1"
anyhow = "1.0.42"
thiserror = "1.0.24"
dioxus = { path = "../../dioxus" }
hecs = "0.7.3"
ctrlc = "3.2.1"
bumpalo = { version = "3.8.0", features = ["boxed"] }
stretch2 = { path = "../../Tinkering/stretch2" }
# stretch2 = { git = "https://github.com/elbaro/stretch2.git" }
