[package]
name = "dioxus"
version = "0.1.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
"license" = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { path="./packages/core", version="0.1.0" }
dioxus-core-macro = { path="./packages/core-macro", version="0.1.0" }
# dioxus-hooks = { path="./packages/hooks", version="0.0.0" }


[features]
default = ["ssr", "hooks", "router", "web", "core", "atoms"]
atoms = []
core = []
ssr = []
hooks = []
router = []
web = []
desktop = []


[profile.dev]
split-debuginfo = "unpacked"


[dev-dependencies]
futures = "0.3.15"
# For the tide ssr examples
# async-std = { version="1.9.0", features=["attributes"] }
# tide = { version="0.16.0" }

# For the livewview example
# tide-websockets = "0.4.0"
# serde_millis = "0.1"
# serde_json = "1"
# serde = { version="1", features=['derive'] }

# For the doc generator
# pulldown-cmark = { version="0.8.0", default-features=false }

# dioxus-webview = { path="./packages/webview", version="0.0.0" }
# dioxus-hooks = { path="./packages/hooks", version="0.0.0" }
rand = "0.8.4"
serde = { version="1.0.126", features=["derive"] }
surf = "2.2.0"


[workspace]
members = [
    "packages/core-macro",
    "packages/core",
    "packages/html-namespace",
    "packages/web",
    "packages/webview"
    # "packages/cli",
    # "packages/atoms",
    # "packages/ssr",
    # "packages/docsite",
    # "packages/router",
    # "packages/inputs",
]
