[workspace]
members = [
    # Built-in
    "packages/dioxus",
    "packages/core",
    "packages/core-macro",
    "packages/router",
    "packages/ssr",
    "packages/webview",
    "packages/web",
    "packages/livehost",
    "packages/vscode-ext",
    # "packages/recoil",
    # "packages/redux",
    # "packages/macro",
    # TODO @Jon, share the validation code
    # "packages/web",
    # "packages/hooks",
    "packages/cli",
    "examples",
    # "packages/html-macro",
    # "packages/html-macro-2",
    #
    #
    #
    # Pulled from percy
    # "packages/html-macro-test",
    # "packages/virtual-dom-rs",
    # "packages/virtual-node",
]
