[package]
name = "dioxus"
version = "0.1.2"
authors = ["Jonathan Kelley"]
edition = "2018"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
license = "MIT/Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react", "wasm"]

[dependencies]
dioxus-core = { path = "./packages/core", version = "^0.1.4" }
dioxus-html = { path = "./packages/html", version = "^0.1.1", optional = true }
dioxus-core-macro = { path = "./packages/core-macro", version = "^0.1.3", optional = true }
dioxus-hooks = { path = "./packages/hooks", optional = true }

dioxus-web = { path = "./packages/web", version = "^0.0.1", optional = true }
dioxus-desktop = { path = "./packages/desktop", optional = true }
dioxus-ssr = { path = "./packages/ssr", optional = true }

dioxus-router = { path = "./packages/router", optional = true }

# dioxus-mobile = { path = "./packages/mobile", optional = true }
# dioxus-liveview = { path = "./packages/liveview", optional = true }

[features]
default = ["macro", "hooks", "html"]

macro = ["dioxus-core-macro"]
hooks = ["dioxus-hooks"]
html = ["dioxus-html"]
router = ["dioxus-router"]
ssr = ["dioxus-ssr"]
web = ["dioxus-web", "dioxus-router/web"]
desktop = ["dioxus-desktop", "dioxus-router/desktop"]


# mobile = ["dioxus-mobile"]
# liveview = ["dioxus-liveview"]


[workspace]
members = [
    "packages/core",
    "packages/core-macro",
    "packages/html",
    "packages/hooks",
    "packages/web",
    "packages/ssr",
    "packages/desktop",
    "packages/mobile",
]

[dev-dependencies]
futures-util = "0.3.17"
log = "0.4.14"
num-format = "0.4.0"
separator = "0.4.1"
serde = { version = "1.0.131", features = ["derive"] }
im-rc = "15.0.0"
anyhow = "1.0.51"
serde_json = "1.0.73"
rand = { version = "0.8.4", features = ["small_rng"] }
tokio = { version = "1.14.0", features = ["full"] }
reqwest = { version = "0.11.8", features = ["json"] }
