[workspace]
members = [
    # Built-in
    "packages/core",
    "packages/macro",
    "packages/hooks",
    "packages/recoil",
    "packages/redux",
    "packages/web",
    #
    #
    #
    # Pulled from percy
    "packages/html-macro",
    "packages/html-macro-test",
    "packages/virtual-dom-rs",
    "packages/virtual-node",
]
