[package]
name = "dioxus"
version = "0.1.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
"license" = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { path = "./packages/core" }
dioxus-core-macro = { path = "./packages/core-macro", optional = true }
dioxus-html = { path = "./packages/html", optional = true }
dioxus-web = { path = "./packages/web", optional = true }
dioxus-webview = { path = "./packages/webview", optional = true }
dioxus-hooks = { path = "./packages/hooks", optional = true }
dioxus-ssr = { path = "./packages/ssr", optional = true }


[features]
default = [
    "core",
    "atoms",
    "macro",
    "ssr",
    "hooks",
    "router",
    "html",
    "web",
    "desktop",
]
atoms = []
macro = ["dioxus-core-macro"]
ssr = ["dioxus-ssr"]
hooks = ["dioxus-hooks"]
router = []
html = ["dioxus-html"]
web = ["dioxus-web"]
desktop = ["dioxus-webview"]

# Core just includes dioxus-core (the only required package)
core = []


[dev-dependencies]
futures = "0.3.15"
log = "0.4.14"
num-format = "0.4.0"
separator = "0.4.1"
serde = { version = "1.0.126", features = ["derive"] }
surf = "2.2.0"
env_logger = "*"
async-std = { version = "1.9.0", features = ["attributes"] }
im-rc = "15.0.0"
rand = { version = "0.8.4", features = ["small_rng"] }
fxhash = "0.2.1"


[workspace]
members = [
    "packages/core",
    "packages/core-macro",
    "packages/html",
    "packages/hooks",
    "packages/web",
    "packages/webview",
    "packages/ssr",
    # "packages/atoms",
    # "packages/docsite",
]
