[workspace]
# members = ["packages/core-macro"]
members = [
    "packages/core-macro",
    "packages/core",
    "packages/web",
    "packages/dioxus",
    "packages/ssr",
    "packages/docsite",
    "packages/recoil",
    "packages/router",
]
# "packages/webview",

# "packages/cli",
# "packages/webview",
# "packages/hooks",
# "packages/ios",

[profile.dev]
split-debuginfo = "unpacked"

# "packages/liveview",
# "packages/3d",

# Built-in
# "packages/webview/client",
# "packages/router",
# "packages/webview",
# "packages/livehost",
# "packages/vscode-ext",
# "packages/recoil",
# "packages/redux",
# "packages/macro",
# TODO @Jon, share the validation code
# "packages/web",
# "packages/cli",
# "examples",
# "packages/html-macro",
