[workspace]
members = [
    # Built-in
    "packages/core",
    "packages/hooks",
    "packages/recoil",
    "packages/redux",
    # TODO @Jon, share the validation code
    # "packages/web",
    "packages/cli",
    "examples",
    "packages/html-macro",
    #
    #
    #
    # Pulled from percy
    # "packages/html-macro-test",
    # "packages/virtual-dom-rs",
    # "packages/virtual-node",
]
