[package]
name = "generational-box"
authors = ["Evan Almloff"]
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.6" }
parking_lot = "0.12.1"

[dev-dependencies]
rand = "0.8.5"
criterion = "0.3"

[features]
default = ["check_generation"]
check_generation = []

[[bench]]
name = "lock"
harness = false
