[package]
name = "dioxus-core-macro"
version = "0.1.1"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Core macro for Dioxus Virtual DOM"
"license" = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
once_cell = "1.7.2"
proc-macro-hack = "0.5.19"
proc-macro2 = "1.0.6"
quote = "1.0"
syn = { version = "1.0.11", features = ["full"] }

# testing
[dev-dependencies]
rustversion = "1.0"
trybuild = "1.0"
