[package]
name = "dioxus-cli-config"
version = "0.4.1"
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Configuration for the Dioxus CLI"
repository = "https://github.com/DioxusLabs/dioxus/"
license = "MIT OR Apache-2.0"
keywords = ["react", "gui", "cli", "dioxus", "wasm"]

[dependencies]
clap = { version = "4.2", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
toml = "0.5.8"
cargo_toml = "0.16.0"

# bundling
tauri-bundler = { version = "=1.3.0", features = ["native-tls-vendored"], optional = true  }
tauri-utils = { version = "=1.4.*", optional = true }
once_cell = "1.18.0"

[features]
default = []
cli = ["tauri-bundler", "tauri-utils"]
