[package]
name = "dioxus-router"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { path = "../core", version = "0.1.3", default-features = false }
dioxus-core-macro = { path = "../core-macro", version = "0.1" }
dioxus-html = { path = "../html", version = "0.0.0", default-features = false }

web-sys = { version = "0.3", features = [
    "Attr",
    "Document",
    "History",
    "HtmlBaseElement",
    "Event",
    "NamedNodeMap",
    "Url",
    "UrlSearchParams",
    "Window",
], optional = true }

serde = "1.0.130"

serde_urlencoded = "0.7"

wasm-bindgen = "0.2"
js-sys = "0.3"
gloo = "0.4"
route-recognizer = "0.3.1"
url = "2.2.2"
url_serde = "0.2.0"


[features]
default = ["web", "derive"]
web = ["web-sys"]
desktop = []
mobile = []
derive = []

[dev-dependencies]
console_error_panic_hook = "0.1.7"
dioxus-web = { path = "../web" }
log = "0.4.14"
wasm-logger = "0.2.0"
