[package]
name = "dioxus-web"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Dioxus VirtualDOM renderer for the web browser using websys"
license = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { path = "../core", version = "0.1.2" }
dioxus-html = { path = "../html" }
js-sys = "0.3"
wasm-bindgen = { version = "0.2.71", features = ["enable-interning"] }
lazy_static = "1.4.0"
wasm-bindgen-futures = "0.4.20"
wasm-logger = "0.2.0"
log = "0.4.14"
fxhash = "0.2.1"
console_error_panic_hook = "0.1.6"
generational-arena = "0.2.8"
wasm-bindgen-test = "0.3.21"
once_cell = "1.8"
async-channel = "1.6.1"
anyhow = "1.0.41"
slotmap = "1.0.3"

futures-util = "0.3.15"

[dependencies.web-sys]
version = "0.3.50"
features = [
    "Comment",
    "Attr",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlSelectElement",
    "HtmlTextAreaElement",
    "EventTarget",
    "HtmlCollection",
    "Node",
    "NodeList",
    "Text",
    "Window",
    "Event",
    "MouseEvent",
    "InputEvent",
    "ClipboardEvent",
    "NamedNodeMap",
    "KeyboardEvent",
    "TouchEvent",
    "WheelEvent",
    "AnimationEvent",
    "TransitionEvent",
    "PointerEvent",
    "FocusEvent",
    "CompositionEvent",
    "DocumentType",
    "CharacterData",
    "SvgElement",
    "SvgAnimatedString",
    "HtmlOptionElement",
]

[profile.release]
lto = true
opt-level = 's'

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
im-rc = "15.0.0"
# rand = { version="0.8.4", features=["small_rng"] }
separator = "0.4.1"
uuid = { version = "0.8.2", features = ["v4", "wasm-bindgen"] }
dioxus-hooks = { path = "../hooks" }
gloo-timers = { version = "0.2.1", features = ["futures"] }
serde = { version = "1.0.126", features = ["derive"] }
surf = { version = "2.2.0", default-features = false, features = [
    "wasm-client",
] }
# wasm-timer = "0.2.5"
