[package]
name = "dioxus-desktop"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Dioxus VirtualDOM renderer for a remote webview instance"
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { path = "../core", version = "0.1.2", features = ["serialize"] }
argh = "0.1.4"
serde = "1.0.120"
serde_json = "1.0.61"
thiserror = "1.0.23"
log = "0.4.13"
html-escape = "0.2.9"
wry = "0.12.2"
futures-channel = "0.3.16"
tokio = { version = "1.12.0", features = ["full"], optional = true }
dioxus-core-macro = { path = "../core-macro" }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["tokio"]


[dev-dependencies]
dioxus-html = { path = "../html" }
dioxus-hooks = { path = "../hooks" }


[build-dependencies]
