[package]
name = "dioxus-hot-reload"
version = "0.1.1"
edition = "2021"
license = "MIT/Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
description = "Hot reloading utilites for Dioxus"
documentation = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react", "hot-reloading"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-rsx = { path = "../rsx" , version = "^0.0.3" }
dioxus-core = { path = "../core", features = ["serialize"], version = "^0.3.2"}
dioxus-html = { path = "../html", features = ["hot-reload-context"], version = "^0.3.0" }

interprocess = { version = "1.2.1" }
notify = "5.0.0"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
serde_json = "1.0.91"
serde = { version = "1", features = ["derive"] }
execute = "0.2.11"
once_cell = "1.17.0"
ignore = "0.4.19"
