[package]
name = "dioxus-coroutines"
version = "0.0.0"
edition = "2018"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
documentation = "https://dioxuslabs.com"
keywords = [
    "dom",
    "ui",
    "userinterface",
    "gui",
    "react",
    "state",
    "management",
    "wasm",
    "web",
    "ssr",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
