[package]
name = "dioxus-core"
version = "0.1.2"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
"license" = "MIT/Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# todo: use wast for faster load/compile
dioxus-core-macro = { path="../core-macro", version="0.1.1" }

# Bumpalo is used as a micro heap backing each component
bumpalo = { version="3.6.0", features=["collections", "boxed"] }

# custom error type
thiserror = "1"

# faster hashmaps
fxhash = "0.2.1"

# Used in diffing
longest-increasing-subsequence = "0.1.0"

# internall used
log = "0.4"

# # Serialize the Edits for use in Webview/Liveview instances
serde = { version="1", features=["derive"], optional=true }

smallvec = "1.6.1"

# Backs scopes and unique keys
slotmap = "1.0.3"

# backs the fiber system for suspended components
# todo: would like to use something smaller or just roll our own futures manually
futures = "0.3.15"


async-std = { version="1.9.0", features=["attributes"] }
appendlist = "1.4.0"

[features]
default = ["serialize"]
# default = []
serialize = ["slotmap/serde", "serde"]
