[package]
name = "dioxus-core"
version = "0.1.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
"license" = "MIT/Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-html-macro = { path = "../html-macro", version = "0.1.0" }
dioxus-core-macro = { path = "../core-macro" }
# Backs some static data
once_cell = "1.5.2"

# Backs the scope creation and reutilization
generational-arena = "0.2.8"

# Bumpalo backs the VNode creation
bumpalo = { version = "3.6.0", features = ["collections"] }
