[package]
name = "dioxus-core"
version = "0.1.2"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"
description = "Core functionality for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
"license" = "MIT/Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# todo: use wast for faster load/compile
dioxus-core-macro = { path = "../core-macro", version = "0.1.1" }

# Backs scopes and graphs between parent and children
generational-arena = { version = "0.2.8", features = ["serde"] }

# Bumpalo backs the VNode creation
bumpalo = { version = "3.6.0", features = ["collections"] }

# Backs hook data - might move away from this arena
typed-arena = "2.0.1"

# custom error type
thiserror = "1.0.23"

# faster hashmaps
fxhash = "0.2.1"

# Used in diffing
longest-increasing-subsequence = "0.1.0"

# internall used
log = "0.4.14"

serde = { version = "1.0.123", features = ["derive"], optional=true }

# todo, remove 
uuid = {version = "0.8.2", features=["serde", "v4"]}

[features]
default = []
