[package]
name = "dioxus-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server_fn = { version = "0.2.4", features = ["stable"] }
server_macro = { path = "server-macro" }

# warp
warp = { version = "0.3.3", optional = true }
http-body = { version = "0.4.5", optional = true }

# axum
axum = { version = "0.6.1", optional = true }
tower-http = { version = "0.4.0", optional = true, features = ["fs"] }
hyper = { version = "0.14.25", optional = true }

# salvo
salvo = { version = "0.37.7", optional = true, features = ["serve-static"] }
serde = "1.0.159"

dioxus-core = { path = "../core", version = "^0.3.0" }
dioxus-ssr = { path = "../ssr", version = "^0.3.0", optional = true }

log = "0.4.17"
once_cell = "1.17.1"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"], optional = true }

[features]
default = []
warp = ["dep:warp", "http-body"]
axum = ["dep:axum", "tower-http", "hyper"]
salvo = ["dep:salvo", "hyper"]
ssr = ["server_fn/ssr", "tokio", "dioxus-ssr"]
