[package]
name = "axum-desktop"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
dioxus = { workspace = true }
axum = { version = "0.6.12", optional = true }
tokio = { workspace = true, features = ["full"], optional = true }
serde = "1.0.159"

[features]
default = []
ssr = ["axum", "tokio", "dioxus/axum"]
desktop = ["dioxus/desktop"]

[[bin]]
name = "client"
path = "src/client.rs"
required-features = ["desktop"]

[[bin]]
name = "server"
path = "src/server.rs"
required-features = ["ssr"]
