[package]
name = "axum-desktop"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
dioxus-desktop = { path = "../../../desktop", optional = true }
dioxus = { path = "../../../dioxus" }
dioxus-router = { path = "../../../router" }
dioxus-server = { path = "../../" }
axum = { version = "0.6.12", optional = true }
tokio = { version = "1.27.0", features = ["full"], optional = true }
serde = "1.0.159"

[features]
default = []
ssr = ["axum", "tokio", "dioxus-server/axum"]
desktop = ["dioxus-desktop"]

[[bin]]
name = "client"
path = "src/client.rs"
required-features = ["desktop"]

[[bin]]
name = "server"
path = "src/server.rs"
required-features = ["ssr"]
