[application]

# dioxus project name
name = "{{project-name}}"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "{{default-platform}}"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "dioxus | ⛺"

[web.watcher]

watch_path = ["src"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.tools]

# use binaryen.wasm-opt for output Wasm file
# binaryen just will trigger in `web` platform
binaryen = { wasm_opt = true }

# use sass auto will auto check sass file and build it.
[application.tools.sass]

version = "1.51.0"

# if auto = true, we will check style array, and translate all sass file to css.
auto = true

# or you can specify some sass file -> css file
files = [
    # some sass file path
    # this file will translate to `/css/test.css`
    "/css/test.sass"
]