[package]
name = "dioxus-router-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-rwlock = "1.3.0"
either = "1.8.0"
futures-channel = "0.3.25"
futures-util = "0.3.25"
regex = { version = "1.6.0", optional = true }
serde = { version = "1.0.147", optional = true }
serde_urlencoded = { version = "0.7.1", optional = true }
url = "2.3.1"
urlencoding = "2.1.2"

[features]
regex = ["dep:regex"]
serde = ["dep:serde", "serde_urlencoded"]
