[package]
name = "dioxus-signals"
authors = ["Jonathan Kelley"]
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { workspace = true }
generational-box = { workspace = true }
log.workspace = true
simple_logger = "4.2.0"

[dev-dependencies]
dioxus = { workspace = true }
dioxus-desktop = { workspace = true }
