[package]
name = "dioxus-signals"
authors = ["Jonathan Kelley"]
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { workspace = true }
slab = { workspace = true }
bumpalo = { version = "3.6" }
