name: github pages

on:
  push:
    paths:
      - docs/**
      - .github/workflows/docs.yml
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: docs
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.10"

      - name: Build
        run: cd docs && mdbook build -d ../build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          clean: false
          token: ${{ secrets.DEPLOY_KEY }} # let's pretend I don't need it for now
