name: Deploy Nightly Docs
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev libxdo-dev
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-02-01
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - uses: ilammy/setup-nasm@v1

      - name: cargo doc
        run: cargo doc --no-deps --workspace --all-features

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: target/doc
          target-folder: api-docs/nightly
          repository-name: dioxuslabs/docsite
          clean: false
          token: ${{ secrets.DEPLOY_KEY }} # let's pretend I don't need it for now

