# Runs whenever a PR is merged:
# - attempt to backports fixes
# - upload nightly docs
# - upload nightly CLI builds
# - upload nightly vscode extension
# - upload benchmarks
# - compute coverge
#
# Note that direct commits to master circumvent this workflow!

# - name: Deploy Nightly Docs.rs
#   uses: JamesIves/github-pages-deploy-action@v4.5.0
#   with:
#     branch: gh-pages
#     folder: target/doc
#     target-folder: api-docs/nightly
#     repository-name: dioxuslabs/docsite
#     clean: false
#     token: ${{ secrets.DEPLOY_KEY }}

# # Attempt to backport a merged pull request to the latest stable release
# #
# # If the backported PR is succesfully merged
# # Any PR without the "breaking" label will be attempted to be backported to the latest stable release

# name: Backport merged pull request
# on:
#   pull_request_target:
#     types: [closed]

# permissions:
#   contents: write # so it can comment
#   pull-requests: write # so it can create pull requests

# jobs:
#   backport:
#     name: Backport pull request
#     runs-on: ubuntu-latest

#     # Don't run on closed unmerged pull requests
#     if: github.event.pull_request.merged
#     steps:
#       - uses: actions/checkout@v4
#       - name: Create backport pull requests
#         uses: korthout/backport-action@v2
# Coverage is disabled until we can fix it
# coverage:
#   name: Coverage
#   runs-on: ubuntu-latest
#   container:
#     image: xd009642/tarpaulin:develop-nightly
#     options: --security-opt seccomp=unconfined
#   steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4
#     - name: Generate code coverage
#       run: |
#         apt-get update &&\
#         apt-get install build-essential &&\
#         apt install libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev -y &&\
#         cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
#     - name: Upload to codecov.io
#       uses: codecov/codecov-action@v2
#       with:
#         fail_ci_if_error: false
