# Whenever commits are merged to main, update or create a PR that bumps the version
# Tracks if changes are semver compatible
# Most likely the changes aren't semver compatible
#
# We want to have a standing "major" update PR and a standing "minor" update PR where fixes are backported
#
# Whenever a PR is made, we want to comment on it:
# - semver compatibility
# - if it's a fix, it should be backported to the minor update PR

on:
  push:
    branches:
      - master

# Generate the minor bump
jobs:
  update_routes:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo, but don't persist credentials, so github uses the GITHUB_TOKEN
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Run cargo workspaces version to generate the version bump PR
      - run: "date > datetime.txt" # create or update a test.txt file

      # And then create the PR
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "My pull request title"
          body: "My pull request body"
          branch: "my-pull-request-base-branch"
          path: "lib/"
          commit-message: "My commit message for uncommitted changes in lib/ folder"
          author: "Lorem J. Ipsum <lorem@example.com>"
          labels: label1, label2
          assignees: user1, user2
          reviewers: user1, user2
          team_reviewers: team1, team2
          auto-merge: squash
          update-pull-request-title-and-body: false

# Generate the major bump
