# Whenever commits are merged to main, update or create a PR that bumps the version
# Tracks if changes are semver compatible
# Most likely the changes aren't semver compatible
#
# We want to have a standing "major" update PR and a standing "minor" update PR where fixes are backported
#
# Whenever a PR is made, we want to comment on it:
# - semver compatibility
# - if it's a fix, it should be backported to the minor update PR
