[package]
name = "dioxus-livehost"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-core = { path = "../core", version = "0.1.2" }
dioxus-web = { path = "../web" }


serde = { version = "1", features = ['derive'] }
tide = "0.16.0"
tide-websockets = "0.3.0"
async-std = { version = "1.8.0", features = ["attributes"] }
log = "0.4"
fern = { version = "0.6.0", features = ["colored"] }
async-channel = "1.5.1"
futures-lite = "1.11.2"
anyhow = "1.0.35"


js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2.71", optional = true }
lazy_static = { version = "1.4.0", optional = true }
wasm-bindgen-futures = { version = "0.4.20", optional = true }


serde_millis = "0.1"
serde_json = "1"
strum = { version = "0.20", features = ["derive"] }


[features]
default = ["client", "server"]
server = []
client = []
